### ISSUE TITLE
the arrow for a local variable does not appear for the first time

### ISSUE THREAD

**Issue by masuhar** [prg-titech/Kanon#8]
The following code should show the arrows for both a and b, but the one for b does not appear when I typed `var b = a;`.  After writing some code in the next line, it appears, and keep appearing even if the added code after `var b = a;` is deleted.

![image](https://user-images.githubusercontent.com/7893790/27468121-e1be7a22-5822-11e7-8680-77ea8c423fae.png)

**Comment by masuhar** [comment]
on FF53.0.3 Windows 32 bit

**Comment by akiou** [comment]
Thank you for your comment. I tried the situation on FF53.0.3 Windows 32 bit, but Kanon was working normally. Could you try the situation again? If Kanon doesn't work, could you tell me the situation more detail? Sorry for any inconvenience.
![2017-07-24 8 54 55](https://user-images.githubusercontent.com/19154263/28504330-28f35ac6-7050-11e7-9d8e-c2997268e3c6.png)

**Comment by masuhar** [comment]
I tried it again and now confirmed that the second arrow appears immediately after I typed `a` in the second line.  I suppose the problem has been resolved.
